//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B201200001_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int Adres_ID { get; set; }
        public Nullable<int> Sehir_ID { get; set; }
        public Nullable<int> ilce_ID { get; set; }
        public Nullable<int> Mahalle_ID { get; set; }
        public Nullable<int> Sokak_ID { get; set; }
        public Nullable<int> Bina_No { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
    
        public virtual ilce ilce { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Mahalle Mahalle { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual Sokak Sokak { get; set; }
    }
}
