//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B201200001_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int Fatura_ID { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<System.DateTime> Siparis_Tarih { get; set; }
        public Nullable<int> Siparis_ID { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
