//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B201200001_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OyuncakTur
    {
        public int Oyuncak_Tur_ID { get; set; }
        public string Oyuncak_Tur { get; set; }
        public Nullable<int> Oyuncak_ID { get; set; }
    
        public virtual Oyuncak Oyuncak { get; set; }
    }
}
