//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B201200001_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyuncak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oyuncak()
        {
            this.OyuncakRenk = new HashSet<OyuncakRenk>();
            this.OyuncakTur = new HashSet<OyuncakTur>();
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int Oyuncak_ID { get; set; }
        public Nullable<int> Oyuncak_Tur_ID { get; set; }
        public Nullable<double> Oyuncak_Agirlik { get; set; }
        public Nullable<double> Oyuncak_Boy { get; set; }
        public Nullable<int> Oyuncak_Renk_ID { get; set; }
        public string Oyuncak_Resim { get; set; }
        public Nullable<double> Oyuncak_Fiyat { get; set; }
        public Nullable<int> Siparis_ID { get; set; }
        public Nullable<int> Magaza_ID { get; set; }
    
        public virtual Magaza Magaza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OyuncakRenk> OyuncakRenk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OyuncakTur> OyuncakTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
