//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B201200001_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.Fatura = new HashSet<Fatura>();
        }
    
        public int Siparis_ID { get; set; }
        public Nullable<int> Oyuncak_Adet { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
        public Nullable<int> Oyuncak_ID { get; set; }
        public Nullable<int> Fatura_ID { get; set; }
        public Nullable<int> Magaza_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Fatura { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Magaza Magaza { get; set; }
        public virtual Oyuncak Oyuncak { get; set; }
    }
}
